--<ScriptOptions statementTerminator=";"/>

ALTER TABLE COMPANY DROP FOREIGN KEY Company_City_FK;

ALTER TABLE ENABLER_ORG DROP FOREIGN KEY Enabler_City_FK;

ALTER TABLE MAKER_SPACES DROP FOREIGN KEY MakerSpaces_City_FK;

ALTER TABLE MEET_UPS DROP FOREIGN KEY Meet_ups_City_FK;

ALTER TABLE City DROP PRIMARY KEY;

ALTER TABLE COMPANY DROP PRIMARY KEY;

ALTER TABLE ENABLER_ORG DROP PRIMARY KEY;

ALTER TABLE MAKER_SPACES DROP PRIMARY KEY;

ALTER TABLE MEET_UPS DROP PRIMARY KEY;

DROP TABLE City;

DROP TABLE COMPANY;

DROP TABLE ENABLER_ORG;

DROP TABLE MAKER_SPACES;

DROP TABLE MEET_UPS;

CREATE TABLE City (
	CITY_NO INT NOT NULL,
	NAME VARCHAR(60),
	BROADBAND_AVERAGE NUMERIC,
	BROADBAND_MEDIAN NUMERIC,
	BROADBAND_MAX NUMERIC,
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	POPULATION INT,
	AVERAGE_OFFICESPACE_PRICE INT,
	ALL_PEOPLE_IN_EMPLOYMENT INT,
	MANGERS_AND_SENIOR_OFFICALS INT,
	PROFESSIONALS INT,
	ASSOC_PROF_AND_TECH INT,
	SKILLED_TRADE INT,
	PERSONAL_SERVICE INT,
	SALES_AND_CUSTOMER_SERVICE INT,
	PROCESS_PLANT_MACHINE_OPS INT,
	ELEMENTARY INT,
	EMPLOYMENT DOUBLE,
	BUSINESS_DENSITY DOUBLE,
	PROPORTION_RESIDENTS_OVR65 DOUBLE,
	JOBDENSITY DOUBLE,
	CLAIMANT_COUNT DOUBLE,
	ECONOMIC_ACTIVITY DOUBLE,
	UNEMPLOYMENT DOUBLE,
	TC_AVAILABLE_PROP INT,
	TC_FAST_BROADBAND INT,
	TC_GOOD_TRANSPORT INT,
	TC_ACCESS_TO_ADVISE INT,
	TC_POSTIVE_REGION INT,
	TC_ACCESS_TO_FINANCE INT,
	TC_POS_ECON_CLIMATE INT,
	TC_STRONG_SKILL_BASE INT,
	PRIMARY KEY (CITY_NO)
);

CREATE TABLE COMPANY (
	COMPANY_NO INT NOT NULL,
	CITY_NO INT NOT NULL,
	WEBSITE_URI VARCHAR(60),
	NAME VARCHAR(60),
	INDUSTRY_TYPE VARCHAR(20),
	STARTUP VARCHAR(10),
	DESCRIPTION VARCHAR(200),
	IMAGE_FILENAME VARCHAR(100),
	FOUNDED DATE,
	TWITTERID VARCHAR(20),
	INDUSTRY_SUBTYPE VARCHAR(30),
	PRIMARY KEY (COMPANY_NO)
);

CREATE TABLE ENABLER_ORG (
	TYPE VARCHAR(20),
	NAME VARCHAR(30) NOT NULL,
	ENABLER_NO INT NOT NULL,
	WEBSITEURI VARCHAR(50),
	CITY_NO INT NOT NULL,
	DESCRIPTION VARCHAR(300),
	ORG_IMAGE_FILENAME VARCHAR(50),
	TWITTERID VARCHAR(20),
	FOUNDED DATE,
	PRIMARY KEY (ENABLER_NO)
);

CREATE TABLE MAKER_SPACES (
	NAME CHAR(20) NOT NULL,
	WEBSITE CHAR(30),
	TWITTERID VARCHAR(20) NOT NULL,
	FACEBOOK VARCHAR(30),
	TYPE VARCHAR(30),
	CURRENT_MEMBERSHIP INT,
	TOTAL_VISITORS INT,
	UNIQUE_VISITORS INT,
	DATE_OPENDED DATE,
	DESCRIPTION VARCHAR(300),
	CITY_NO INT NOT NULL,
	MAKER_NO INT NOT NULL,
	PRIMARY KEY (MAKER_NO)
);

CREATE TABLE MEET_UPS (
	NAME VARCHAR(30),
	DESCRIPTION VARCHAR(300),
	NO_OF_MEMBERS INT,
	URI VARCHAR(30),
	MEETINGS_COMING_UP INT,
	ABOUT VARCHAR(200),
	NO_OF_PAST_MEETINGS INT,
	CITY_NO INT NOT NULL,
	MEET_UP_NO INT NOT NULL,
	PRIMARY KEY (MEET_UP_NO)
);

ALTER TABLE COMPANY ADD CONSTRAINT Company_City_FK FOREIGN KEY (CITY_NO)
	REFERENCES City (CITY_NO)
	ON DELETE CASCADE;

ALTER TABLE ENABLER_ORG ADD CONSTRAINT Enabler_City_FK FOREIGN KEY (CITY_NO)
	REFERENCES City (CITY_NO)
	ON DELETE CASCADE;

ALTER TABLE MAKER_SPACES ADD CONSTRAINT MakerSpaces_City_FK FOREIGN KEY (CITY_NO)
	REFERENCES City (CITY_NO)
	ON DELETE CASCADE;

ALTER TABLE MEET_UPS ADD CONSTRAINT Meet_ups_City_FK FOREIGN KEY (CITY_NO)
	REFERENCES City (CITY_NO)
	ON DELETE CASCADE;

